### ISSUE TITLE
TypeError: e.referenceImages.entities.toReversed is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by Loplaus555** [AnyGogin31/InvokeAI-Colab#1] opened 2024-10-06 03:28 UTC
Everything seems to work fine, but clicking canvas gives this error every time and refreshing does nothing.

**Comment by AnyGogin31** [comment] 2024-10-06 05:21
Most likely this is a problem of InvokeAI itself, this project only helps to host it on cloud servers. Today I will try to cause this error and write what the problem is.

**Comment by AnyGogin31** [comment] 2024-10-06 05:59
I don't have enough information to reproduce this error, but it's definitely an issue with InvokeAI itself. You might want to wait for a release that fixes this. You can also submit this issue to InvokeAI to ensure it gets resolved in the next release.

**Comment by Loplaus555** [comment] 2024-10-06 06:58
Will do. It only did this by clicking the canvas at first. Now it's doing this every time I open the tunnel.

**Comment by AnyGogin31** [comment] 2024-10-06 08:00
Have you tried deleting the runtime and running all the steps again?

**Comment by Loplaus555** [comment] 2024-10-06 15:46
Yes and I get the same error.

**Comment by AnyGogin31** [comment] 2024-10-06 16:18
Got it. Now I'll be watching for the answer to the error you left at InvokeAI.

**Comment by Loplaus555** [comment] 2024-10-06 17:06
I get the typeError when opening the link for the ui, but an option to refresh to the model tab. Reloading loads up the ui and every other tab works except the cavas which causes the the same typeError. Very strange.

**Comment by AnyGogin31** [comment] 2024-10-06 17:38
No matter how hard I try, I can't reproduce this error. Here are a few tips that might help (though they don't guarantee a solution).

1. Clear the cookies of the site where your webui is running.
2. Update your browser to the latest version.
3. If you can access your webui, go to the settings, clear the cache, and click restart webui.
4. Try launching your webui without loading data from Google Drive first.

If none of this helps, I'm afraid I’m out of options. I have no issues with launching or generating.

**Comment by Loplaus555** [comment] 2024-10-06 23:23
I tested out on my phone with kiwi. It indeed WAS my browser. That was embarrassing.

**Closed as completed** 2024-10-07 00:47 UTC
